import ForgotPasswordScreen from "../../screens/ForgotPasswordScreen/index";
export type RootStackParamList = {
  AnimatedExample: undefined;
  ChuyenKhoaScreen: undefined;
  Code: undefined;
  DatKhamScreen: undefined;
  FingerPrint: undefined;
  GoiKhamScreen: undefined;
  HomeScreen: undefined;
  InformationUserScreen: undefined;
  InformationCodeScreen: undefined;
  LoginScreen: undefined;
  MapsScreen: undefined;
  PromotionScreen: undefined;
  RegisterScreen: undefined;
  ServiceScreen: undefined;
  TouchId: undefined;
  VerifyCodeScreen: undefined;
  VipCardScreen: undefined;
  WebMaps: undefined;
  NewsScreen: undefined;
  ScrollNews: undefined;
  InformationNewScreen: undefined;
  News: undefined;
  ForgotPasswordScreen: undefined;
  DrawerComponent: undefined;
  OnboardingScreen: undefined;
  Header_wrapper: undefined;
  CameraScreen: undefined;
  CameraComponent: undefined;
};
